apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-webui
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.name }}-webui
